### ISSUE TITLE
pip install zksync2 fail

### ISSUE THREAD

**Issue by necaluo** [zksync-sdk/zksync2-python#32] opened 2023-05-19 14:56 UTC
It not works for pip install zksync2. Get the error:
 
Building wheels for collected packages: pysha3
  Building wheel for pysha3 (setup.py) ... error
  error: subprocess-exited-with-error
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pysha3

**Comment by Nazaroni** [comment] 2023-05-19 21:21
I have the same error (Windows 10. Python3.10.5)

**Comment by danijelTxFusion** [comment] 2023-05-19 22:46
This is issue a duplicate of [#3](https://github.com/zksync-sdk/zksync2-python/issues/3#issuecomment-1499090601)

**Closed** 2023-05-19 22:47 UTC
